apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brigade2-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - brigade2.lb.djnd.si
      secretName: brigade2-nginx-tls
  rules:
    - host: brigade2.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brigade2-nginx
                port:
                  number: 80
