apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: brigade2
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: brigade2
    newName: rg.fr-par.scw.cloud/djnd/brigade2
    newTag: 'a7945a55750fba8c2bd0095a0477734e42ad1938'
